### ISSUE TITLE
Error analysing PR244 run 47

### ISSUE THREAD

**Issue by padsley** [padsley/k600analyser#48]
For context: runs 43-46 and 48 and 49 analyse just fine.

I'm going to try running it on my laptop at some point to see if that makes a difference.

==================================================================== 47  

lut x1 offset: 0 
lut u1 offset: 0 
lut x2 offset: 0 
lut u2 offset: 0 
[Analyzer,INFO] Set run number 47 in ODB
Cannot open message log file /scratch/data/SiDetectorTests/midas.log
/experiment-data/PR244/run00047.mid.gz:550000  events
 *** Break *** segmentation violation

===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================

Thread 2 (Thread 0x7f49b0fee700 (LWP 713)):
#0  0x0000003cbfa0ea5d in accept () from /lib64/libpthread.so.0
#1  0x00007f49b6b3a944 in TUnixSystem::AcceptConnection(int) () from /afs/tlabs.ac.za/user/p/padsley/root/lib/libCore.so
#2  0x00007f49b5757d6c in TServerSocket::Accept(unsigned char) () from /afs/tlabs.ac.za/user/p/padsley/root/lib/libNet.so
#3  0x00000000004163ee in root_socket_server (arg=<value optimized out>) at src/mana.cxx:5272
#4  0x00007f49b2e7f8fd in TThread::Function(void*) () from /afs/tlabs.ac.za/user/p/padsley/root/lib/libThread.so
#5  0x0000003cbfa079d1 in start_thread () from /lib64/libpthread.so.0
#6  0x0000003cbf2e88fd in clone () from /lib64/libc.so.6

Thread 1 (Thread 0x7f49b2e551c0 (LWP 705)):
#0  0x0000003cbf2ac65d in waitpid () from /lib64/libc.so.6
#1  0x0000003cbf23e609 in do_system () from /lib64/libc.so.6
#2  0x0000003cbf23e940 in system () from /lib64/libc.so.6
#3  0x00007f49b6b41298 in TUnixSystem::StackTrace() () from /afs/tlabs.ac.za/user/p/padsley/root/lib/libCore.so
#4  0x00007f49b6b40113 in TUnixSystem::DispatchSignals(ESignals) () from /afs/tlabs.ac.za/user/p/padsley/root/lib/libCore.so
#5  <signal handler called>
#6  0x0000000000431a8d in focal_event (pheader=0x7f49a7e56010, pevent=0x7f49a7e56020) at f-plane.c:2483
#7  0x000000000041c7cb in process_event (par=0x6912e0, pevent=0x7f49a7e56010) at src/mana.cxx:3155
#8  0x000000000041cd62 in analyze_run (run_number=47, input_file_name=0x7fffe469e940 "/experiment-data/PR244/run00047.mid.gz", output_file_name=<value optimized out>) at src/mana.cxx:4175
#9  0x000000000041d292 in loop_runs_offline () at src/mana.cxx:4363
#10 0x000000000041dac5 in main (argc=<value optimized out>, argv=<value optimized out>) at src/mana.cxx:5576
===========================================================

The lines below might hint at the cause of the crash.
If they do not help you then please submit a bug report at
http://root.cern.ch/bugs. Please post the ENTIRE stack trace
from above as an attachment in addition to anything else
that might help us fixing this issue.
===========================================================
#6  0x0000000000431a8d in focal_event (pheader=0x7f49a7e56010, pevent=0x7f49a7e56020) at f-plane.c:2483
#7  0x000000000041c7cb in process_event (par=0x6912e0, pevent=0x7f49a7e56010) at src/mana.cxx:3155
#8  0x000000000041cd62 in analyze_run (run_number=47, input_file_name=0x7fffe469e940 "/experiment-data/PR244/run00047.mid.gz", output_file_name=<value optimized out>) at src/mana.cxx:4175
#9  0x000000000041d292 in loop_runs_offline () at src/mana.cxx:4363
#10 0x000000000041dac5 in main (argc=<value optimized out>, argv=<value optimized out>) at src/mana.cxx:5576
===========================================================

[Analyzer,ERROR] [midas.c:1914:,ERROR] cm_disconnect_experiment not called at end of program
Cannot open message log file /scratch/data/SiDetectorTests/midas.log

**Comment by padsley** [comment]
I think that these errors must have been something to do with /experiment-data but I have no idea what. I've not seen any of them for a while so we might we well close this issue and assume that everything is fine for now.
